services:
  app:
    container_name: hopi-hari-experience-backend
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app/
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run dev
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
